### ISSUE TITLE
Login screen impassible

### ISSUE THREAD

**Issue by aren-cllc** [shiftos-game/ShiftOS#71]
The screen during OOBE for logging into an existing account doesn't work.

**Comment by ComputeLinux** [comment]
fixed

**Comment by ComputeLinux** [comment]
forgot to close this

**Comment by MichaelTheShifter** [comment]
Easy fix: Simply make the mouse click event scroll the terminal to the bottom. BAM.

**Comment by MichaelTheShifter** [comment]
WAIT. DRUNKY MICHAEL. YOU REFERENCED THE WRONG ISSUE.

**Comment by MichaelTheShifter** [comment]
@ComputeLinux you're assigned to this. FIX IT. xD

**Comment by aren-cllc** [comment]
Haha

**Comment by MichaelTheShifter** [comment]
I have firstly made a login button available to the initial OOBE when you're asked to register. It uses the same login sequence, so if THAT works, then this works.

I have secondly TESTED that system, and it works. So this issue is fixed. There was never a bug. It was probably just user error... remember that an incorrect set of credentials won't let you in.
